### ISSUE TITLE
Timeoutエラー後にFailed to get a spread analysis resultが続く

### ISSUE THREAD

**Issue by BabyStarRamen** [bitrinjani/r2#108]
Timeoutエラー後にFailed to get a spread analysis resultが続きました。
INFOとDEBUGを貼り付けます。再起動後は通常処理に戻りました。

2018-02-11 16:26:30.669 INFO ---------------------POSITION---------------------
2018-02-11 16:26:30.669 INFO Net Exposure: 0 BTC
2018-02-11 16:26:30.669 INFO Bitflyer  :      0 BTC, LongAllowed: OK, ShortAllowed: NG (Stability: 10)
2018-02-11 16:26:30.670 INFO BitflyerFX:      0 BTC, LongAllowed: OK, ShortAllowed: OK (Stability: 10)
2018-02-11 16:26:30.670 INFO --------------------------------------------------
2018-02-11 16:26:30.670 INFO --------------------ARBITRAGER--------------------
2018-02-11 16:26:30.670 INFO Looking for opportunity...
2018-02-11 16:26:30.682 INFO Best ask         : Bitflyer   Ask 887,500 3.197
2018-02-11 16:26:30.682 INFO Best bid         : BitflyerFX Bid 897,400 1.086
2018-02-11 16:26:30.682 INFO Spread           : -9900
2018-02-11 16:26:30.682 INFO Available volume : 1.085
2018-02-11 16:26:30.682 INFO Target volume    : 0.01
2018-02-11 16:26:30.683 INFO Expected profit  : 82 (0.919%)
2018-02-11 16:26:30.683 INFO Target profit is smaller than min profit.
2018-02-11 16:26:30.683 INFO --------------------------------------------------
2018-02-11 16:26:38.013 ERROR network timeout at: https://api.bitflyer.jp/v1/board
2018-02-11 16:26:38.013 ERROR network timeout at: https://api.bitflyer.jp/v1/board?product_code=FX_BTC_JPY
2018-02-11 16:26:38.018 INFO ---------------------POSITION---------------------
2018-02-11 16:26:38.018 INFO Net Exposure: 0 BTC
2018-02-11 16:26:38.018 INFO Bitflyer  :      0 BTC, LongAllowed: OK, ShortAllowed: NG (Stability: 9)
2018-02-11 16:26:38.019 INFO BitflyerFX:      0 BTC, LongAllowed: OK, ShortAllowed: OK (Stability: 9)
2018-02-11 16:26:38.019 INFO --------------------------------------------------
2018-02-11 16:26:38.019 INFO --------------------ARBITRAGER--------------------
2018-02-11 16:26:38.020 INFO Looking for opportunity...
2018-02-11 16:26:38.026 WARN Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker configs. No best bid was found.
2018-02-11 16:26:38.026 INFO --------------------------------------------------
2018-02-11 16:26:43.591 ERROR request to https://api.bitflyer.jp/v1/me/getpositions?product_code=FX_BTC_JPY failed, reason: read ECONNRESET
2018-02-11 16:26:44.025 ERROR network timeout at: https://api.bitflyer.jp/v1/board?product_code=FX_BTC_JPY
2018-02-11 16:26:44.189 INFO ---------------------POSITION---------------------
2018-02-11 16:26:44.189 INFO Net Exposure: 0 BTC
2018-02-11 16:26:44.189 INFO Bitflyer  :      0 BTC, LongAllowed: OK, ShortAllowed: NG (Stability: 8)
2018-02-11 16:26:44.190 INFO BitflyerFX:      0 BTC, LongAllowed: OK, ShortAllowed: OK (Stability: 7)
2018-02-11 16:26:44.190 INFO --------------------------------------------------
2018-02-11 16:26:44.190 INFO --------------------ARBITRAGER--------------------
2018-02-11 16:26:44.190 INFO Looking for opportunity...
2018-02-11 16:26:44.199 WARN Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker configs. No best bid was found.
2018-02-11 16:26:44.200 INFO --------------------------------------------------
2018-02-11 16:26:50.038 ERROR network timeout at: https://api.bitflyer.jp/v1/board?product_code=FX_BTC_JPY
2018-02-11 16:26:50.047 INFO ---------------------POSITION---------------------
2018-02-11 16:26:50.047 INFO Net Exposure: 0 BTC
2018-02-11 16:26:50.047 INFO Bitflyer  :      0 BTC, LongAllowed: OK, ShortAllowed: NG (Stability: 8)
2018-02-11 16:26:50.048 INFO BitflyerFX:      0 BTC, LongAllowed: NG, ShortAllowed: NG (Stability: 6)
2018-02-11 16:26:50.048 INFO --------------------------------------------------
2018-02-11 16:26:50.048 INFO --------------------ARBITRAGER--------------------
2018-02-11 16:26:50.049 INFO Looking for opportunity...
2018-02-11 16:26:50.066 WARN Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker configs. No best bid was found.
2018-02-11 16:26:50.067 INFO --------------------------------------------------
2018-02-11 16:26:51.765 INFO ---------------------POSITION---------------------
2018-02-11 16:26:51.765 INFO Net Exposure: 0 BTC
2018-02-11 16:26:51.765 INFO Bitflyer  :      0 BTC, LongAllowed: OK, ShortAllowed: NG (Stability: 8)
2018-02-11 16:26:51.766 INFO BitflyerFX:      0 BTC, LongAllowed: NG, ShortAllowed: NG (Stability: 6)
2018-02-11 16:26:51.766 INFO --------------------------------------------------
2018-02-11 16:26:51.766 INFO --------------------ARBITRAGER--------------------
2018-02-11 16:26:51.766 INFO Looking for opportunity...
2018-02-11 16:26:51.777 WARN Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker configs. No best bid was found.
2018-02-11 16:26:51.777 INFO --------------------------------------------------

2018-02-11 16:26:44.199 WARN [OppotunitySearcher] Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker configs. No best bid was found.
2018-02-11 16:26:44.200 DEBUG [OppotunitySearcher] Error: No best bid was found.
    at SpreadAnalyzer.<anonymous> (/mnt/usb1/home/XXXXXXX/r2/dist/SpreadAnalyzer.js:66:23)
    at Generator.next (<anonymous>)
    at /mnt/usb1/home/XXXXXXX/r2/dist/SpreadAnalyzer.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/usb1/home/XXXXXXX/r2/dist/SpreadAnalyzer.js:15:12)
    at SpreadAnalyzer.analyze (/mnt/usb1/home/XXXXXXX/r2/dist/SpreadAnalyzer.js:39:16)
    at OppotunitySearcher.<anonymous> (/mnt/usb1/home/XXXXXXX/r2/dist/OpportunitySearcher.js:61:72)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/usb1/home/XXXXXXX/r2/dist/OpportunitySearcher.js:16:58)
    at <anonymous>

**Comment by bitrinjani** [comment]
bitFlyerのAPIが5秒以上レスポンスを返さないときにそのエラーが発生します。bitFlyer側の問題だと思われます。
なお、[こちらに記載](https://github.com/bitrinjani/bitflyer-fx)していますが、BitflyerとBitflyerFXの両方を有効にすることはお勧めしません。

>標準のBitflyerブローカーとこのBitflyerFXブローカーを同時に有効にしないでください。取引所のAPI使用回数制限に達する可能性があります。

**Comment by BabyStarRamen** [comment]
再起動後に直ったため、タイムアウト後の処理に・・と思い投稿しました。
bitFlyer側の問題の旨、承知しました。
早々の回答ありがとうございました。
