### ISSUE TITLE
Bitflyer-Fxプラグイン導入時のエラー　"error unable to find BitflyerFx package"

### ISSUE THREAD

**Issue by oriori5537** [bitrinjani/r2#129]
Bitflyer-Fxのブローカー情報をconfigに書きnpm startさせましたが、" error unable to find BitflyerFx package"と出てきて起動出来ません。
git cloneでBitflyer-Fxをクローンしたり、@bitr下にBitflyer-Fxファイルを置き、npm install Bitflyer-Fxなども試しましたが変わらずエラーが出ます。
これは本体のバージョンとプラグインのバージョンが異なるために起こるのでしょうか? 
どなたか分かる方居られましたらご教授お願いします。

[debug log] 
2018-03-26 05:20:20.813 INFO [AppRoot] サービスを開始中...
2018-03-26 05:20:21.085 ERROR [AppRoot] Unabled to find BitflyerFX package.
2018-03-26 05:20:21.086 DEBUG [AppRoot] Error: Unabled to find BitflyerFX package.
    at AppRoot.<anonymous> (C:\Users\oriori\r2\dist\AppRoot.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\oriori\r2\dist\AppRoot.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by Connie-Wild** [comment]
一度全てを削除した上で、
```
1. git clone https://github.com/bitrinjani/r2.git
2. cd r2
3. npm install
4. npm install @bitr/bitflyer-fx
5. npm test
```
を実行してください。
npm testでエラーが出るなら、実行してる環境に問題があります。
nodejsのバージョンが8.x系じゃないとか。

**Comment by oriori5537** [comment]
->Connie-Wildさんへ

Connieさんの手順通りにもう一度再インストールするとエラーも起きず上手く行きました。自分であちこち手を入れており、再インストールするという基本的な解決策をすっかり失念しておりました。
ご迷惑おかけして申し訳ありませんでした。
次は自力で解決出来るようこれからも切磋琢磨して行きたいと思っております。
ありがとうございました。
