### ISSUE TITLE
npm start 実行時のエラー

### ISSUE THREAD

**Issue by ghost** [bitrinjani/r2#130]
素晴らしいツールを公開いただきありがとうございます。

早速、いくつかの取引所アカウント発行をして試みて見ましたが、
以下のエラーが発生します。
解決策と、原因をご教示いただけませんでしょうか？

TypeError: util_1.promisify is not a function
    at Object.<anonymous> (/Users/user/Tools/r2/dist/ReportService.js:38:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ((プロジェクトインストールフォルダ)/r2/dist/AppRoot.js:19:25)
    at Module._compile (module.js:570:32)

**Comment by Connie-Wild** [comment]
@Yoshio-M さん
実行環境等なにも明記されてません。
逆にあなたが同じ質問をされて、そのエラーメッセージだけで解決策と原因を答えることができますか？
・Windows？Linux？macOS？
・git clone したディレクトリの場所
・nodejsのバージョン
・実施したr2のインストール手順

**Comment by ghost** [comment]
@Connie-Wild さん

失礼いたしました、他にどういった情報が必要かを伝えるべきでした。
以後、このような質問をする場合は、気をつけるようにいたします。ありがとうございます。

今回のエラーですが、node.jsのバージョンが元々はv6インストールしており、
改めてv8をインストールしましたが、そのインストールがうまくできていなかった為
発生していたようでした。
v6をアンインストール後、改めてv8をインストールしたところ上手く起動しました。

お時間を取らせてしまい、申し訳ございませんでした。
