### ISSUE TITLE
Failed to get a spread analysis result. 

### ISSUE THREAD

**Issue by ynzheng** [bitrinjani/r2#23]
2017-12-25 10:21:27.085 DEBUG [WebClient] Response content from https://api.quoine.com/trading_accounts: [{"id":412243,"leverage_level":10,"m$
2017-12-25 10:21:27.089 DEBUG [PositionService] Finished refresh.
2017-12-25 10:21:27.089 DEBUG [PositionService] Started PositionService.
2017-12-25 10:21:27.094 INFO [Arbitrager] Starting Arbitrager...
2017-12-25 10:21:27.095 INFO [Arbitrager] Started Arbitrager.
2017-12-25 10:21:27.096 INFO [AppRoot] Successfully started the service.
2017-12-25 10:21:29.692 DEBUG [QuoteAggregator] Aggregating quotes...
2017-12-25 10:21:29.693 DEBUG [WebClient] Sending HTTP request... URL: https://api.bitflyer.jp/v1/board Request: {"timeout":5000}
2017-12-25 10:21:29.695 DEBUG [WebClient] Sending HTTP request... URL: https://api.quoine.com/products/5/price_levels Request: {"timeout":50$
2017-12-25 10:21:29.744 DEBUG [WebClient] Response from https://api.quoine.com/products/5/price_levels. Status Code: 200 (OK)
2017-12-25 10:21:29.753 DEBUG [WebClient] Response from https://api.bitflyer.jp/v1/board. Status Code: 200 (OK)
2017-12-25 10:21:29.814 DEBUG [QuoteAggregator] New quotes have been set.
2017-12-25 10:21:29.815 DEBUG [QuoteAggregator] Calling onQuoteUpdated...
2017-12-25 10:21:29.816 INFO [PositionService] ---------------------POSITION---------------------
2017-12-25 10:21:29.818 INFO [PositionService] Net Exposure: -1.101 BTC
2017-12-25 10:21:29.820 INFO [PositionService] Bitflyer  : 0.001 BTC, LongAllowed: OK, ShortAllowed: NG
2017-12-25 10:21:29.822 INFO [PositionService] Quoine    : -1.102 BTC, LongAllowed: OK, ShortAllowed: NG
2017-12-25 10:21:29.823 INFO [PositionService] --------------------------------------------------
2017-12-25 10:21:29.824 DEBUG [PositionService] {"Bitflyer":{"broker":"Bitflyer","btc":0.00089896,"allowedLongSize":1.09910104,"allowedShort$
2017-12-25 10:21:29.824 INFO [Arbitrager] --------------------ARBITRAGER--------------------
2017-12-25 10:21:29.826 INFO [Arbitrager] Looking for opportunity...
2017-12-25 10:21:29.835 WARN [Arbitrager] Failed to get a spread analysis result. Check maxLongPosition and maxShortPosition in the broker c$
2017-12-25 10:21:29.836 DEBUG [Arbitrager] Error: No best bid was found.
    at SpreadAnalyzerImpl.<anonymous> (/home/username/bitrinjani/r2/dist/SpreadAnalyzerImpl.js:67:23)
    at Generator.next (<anonymous>)
    at /home/username/bitrinjani/r2/dist/SpreadAnalyzerImpl.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/username/bitrinjani/r2/dist/SpreadAnalyzerImpl.js:15:12)
    at SpreadAnalyzerImpl.analyze (/home/username/bitrinjani/r2/dist/SpreadAnalyzerImpl.js:38:16)
    at ArbitragerImpl.<anonymous> (/home/username/bitrinjani/r2/dist/ArbitragerImpl.js:83:70)
    at Generator.next (<anonymous>)
    at fulfilled (/home/username/bitrinjani/r2/dist/ArbitragerImpl.js:16:58)
    at <anonymous>

**Comment by ynzheng** [comment]
it will always show this error after starting for a while ...what`wong there   ....thanks

**Comment by Connie-Wild** [comment]
ShortAllowed is NG at all exchanges.
In this case, spread analysis is not possible.
Check maxLongPosition and maxShortPosition in the broker.
