### ISSUE TITLE
BitflyerFXのmaxLongPosition, maxShortPositionの設定について

### ISSUE THREAD

**Issue by unitarocom** [bitrinjani/r2#99]
素晴らしいスクリプトの公開ありがとうございます。
BitflyerFXのプラグインを導入後、デモで裁定機会を得られたので本番モードで回してみました。
QUOINEXは口座開設中でAPI設定ができてませんので、コインチェックとBFのみで回しました。
予算はCC,BFとも1万ちょいで試しております。

CCの設定は
      "maxLongPosition": 0.15,
      "maxShortPosition": 0.15,

BFFXの設定は
      "maxLongPosition": 0.02,
      "maxShortPosition": 0.02,

で設定をしたところオーダー送信を試みてるようなのですが、下記のエラーが出ます。
`ERROR [Arbitrager] Not implemented.`
BFFXの設定は0.02~0.15まで試しました。

`2018-02-02 15:52:29.797 INFO [Arbitrager] --------------------ARBITRAGER--------------------
2018-02-02 15:52:29.797 INFO [OppotunitySearcher] 裁定機会をチェック中...
2018-02-02 15:52:29.803 INFO [OppotunitySearcher] ベストアスク           : Coincheck  Ask 909,000 0.05
2018-02-02 15:52:29.803 INFO [OppotunitySearcher] ベストビッド           : BitflyerFX Bid 921,300 0.07
2018-02-02 15:52:29.803 INFO [OppotunitySearcher] スプレッド　           : -12300
2018-02-02 15:52:29.803 INFO [OppotunitySearcher] 裁定可能数量           : 0.05
2018-02-02 15:52:29.804 INFO [OppotunitySearcher] 目標数量　　           : 0.01
2018-02-02 15:52:29.804 INFO [OppotunitySearcher] 予想収益　　           : 123 (1.344%)
2018-02-02 15:52:29.804 INFO [OppotunitySearcher] >>裁定機会を発見。
2018-02-02 15:52:29.804 INFO [PairTrader] >>オーダーを送信中... 目標価格 Coincheck  Ask 909,000 0.05
2018-02-02 15:52:29.806 INFO [PairTrader] >>オーダーを送信中... 目標価格 BitflyerFX Bid 921,300 0.07
2018-02-02 15:52:29.806 ERROR [Arbitrager] Not implemented.
2018-02-02 15:52:29.807 INFO [Arbitrager] >>5000 ms スリープ中...
2018-02-02 15:52:34.807 INFO [Arbitrager] --------------------------------------------------
2018-02-02 15:52:35.793 INFO [PositionService] ---------------------POSITION---------------------
2018-02-02 15:52:35.793 INFO [PositionService] Net Exposure: 0 BTC
2018-02-02 15:52:35.793 INFO [PositionService] Coincheck :      0 BTC, 買い試行許可: NG, 売り試行許可: NG (Stability: 7)
2018-02-02 15:52:35.793 INFO [PositionService] BitflyerFX:      0 BTC, 買い試行許可: NG, 売り試行許可: NG (Stability: 7)
2018-02-02 15:52:35.793 INFO [PositionService] --------------------------------------------------
2018-02-02 15:52:35.793 INFO [Arbitrager] --------------------ARBITRAGER--------------------
2018-02-02 15:52:35.793 INFO [OppotunitySearcher] 裁定機会をチェック中...
2018-02-02 15:52:35.798 WARN [OppotunitySearcher] スプレッド解析結果の取得に失敗しました。取引所設定のmaxLongPosition, maxShortPositionが十分に大きいか確認してください。 ベストビッドが見つかりませんでした。
2018-02-02 15:52:35.798 INFO [Arbitrager] --------------------------------------------------`

設定としてどのあたりが間違っているのかご教示いただけますでしょうか？

**Comment by Connie-Wild** [comment]
Not implemented.=未実装
debug.logがなければ原因を調べるのは難しいかと思います。

下の注意分を認識した上で利用されてると思ってよろしいですね。
~~~~~
現在のところ、BTC-FX/JPY価格はBTC/JPY価格とまったく異なり、その価格変動は相関していません。minTargetProfitPercent等のパラメタータ設定が難しいため、その動作について十分に理解していない方はこのプラグインを使用しないでください。

**Comment by bitrinjani** [comment]
おそらくR2本体とプラグインのバージョンがずれているのではないでしょうか?
どちらかが古いとそのエラーが出る可能性があります。
再インストールするか、`git pull`で本体を最新版にした上でプラグインをnpm uninstall/installしてみてください。

**Comment by bitrinjani** [comment]
>QUOINEXは口座開設中でAPI設定ができてませんので、コインチェックとBFのみで回しました。

なお、Coincheckは現在APIでの取引を受け付けていないので、仮にbitFlyerのオーダーが通っても、Coincheckのオーダー送信でエラーになります。

**Comment by unitarocom** [comment]
>debug.logがなければ原因を調べるのは難しいかと思います。

遅くなりすみません。
debug.logを貼らせていただきます。
BitflyerFXについての注意文についてはリスクも含めて理解してるつもりです。

2018-02-02 16:40:09.463 DEBUG [QuoteAggregator] Aggregating quotes...
2018-02-02 16:40:09.463 DEBUG [WebClient] Sending HTTP request... URL: https://coincheck.com/api/order_books Request: {"timeout":5000}
2018-02-02 16:40:09.464 DEBUG [WebClient] Sending HTTP request... URL: https://api.bitflyer.jp/v1/board?product_code=FX_BTC_JPY Request: {"timeout":5000}
2018-02-02 16:40:09.525 DEBUG [WebClient] Response from https://coincheck.com/api/order_books. Status Code: 200 (OK) 
2018-02-02 16:40:09.559 DEBUG [WebClient] Response from https://api.bitflyer.jp/v1/board?product_code=FX_BTC_JPY. Status Code: 200 (OK) 
2018-02-02 16:40:09.606 DEBUG [QuoteAggregator] New quotes have been set.
2018-02-02 16:40:09.606 DEBUG [QuoteAggregator] Calling onQuoteUpdated...
2018-02-02 16:40:09.607 INFO [PositionService] ---------------------POSITION---------------------
2018-02-02 16:40:09.607 INFO [PositionService] Net Exposure: 0 BTC
2018-02-02 16:40:09.607 INFO [PositionService] Coincheck :      0 BTC, 買い試行許可: NG, 売り試行許可: NG (Stability: 7)
2018-02-02 16:40:09.607 INFO [PositionService] BitflyerFX:      0 BTC, 買い試行許可: NG, 売り試行許可: NG (Stability: 7)
2018-02-02 16:40:09.607 INFO [PositionService] --------------------------------------------------
2018-02-02 16:40:09.607 DEBUG [PositionService] {"Coincheck":{"broker":"Coincheck","btc":0,"allowedLongSize":0.15,"allowedShortSize":0.15,"longAllowed":false,"shortAllowed":false},"BitflyerFX":{"broker":"BitflyerFX","btc":0,"allowedLongSize":0.15,"allowedShortSize":0.15,"longAllowed":false,"shortAllowed":false}}
2018-02-02 16:40:09.607 INFO [Arbitrager] --------------------ARBITRAGER--------------------
2018-02-02 16:40:09.607 INFO [OppotunitySearcher] 裁定機会をチェック中...
2018-02-02 16:40:09.610 WARN [OppotunitySearcher] スプレッド解析結果の取得に失敗しました。取引所設定のmaxLongPosition, maxShortPositionが十分に大きいか確認してください。 ベストビッドが見つかりませんでした。
2018-02-02 16:40:09.610 DEBUG [OppotunitySearcher] Error: ベストビッドが見つかりませんでした。
    at SpreadAnalyzer.<anonymous> (C:\Users\unitaro\r2-master\dist\SpreadAnalyzer.js:66:23)
    at Generator.next (<anonymous>)
    at C:\Users\unitaro\r2-master\dist\SpreadAnalyzer.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\unitaro\r2-master\dist\SpreadAnalyzer.js:15:12)
    at SpreadAnalyzer.analyze (C:\Users\unitaro\r2-master\dist\SpreadAnalyzer.js:39:16)
    at OppotunitySearcher.<anonymous> (C:\Users\unitaro\r2-master\dist\OpportunitySearcher.js:59:72)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\unitaro\r2-master\dist\OpportunitySearcher.js:16:58)
    at <anonymous>
2018-02-02 16:40:09.610 INFO [Arbitrager] --------------------------------------------------
2018-02-02 16:40:09.611 DEBUG [QuoteAggregator] onQuoteUpdated done.
2018-02-02 16:40:09.611 DEBUG [QuoteAggregator] Aggregated.
2018-02-02 16:40:09.850 DEBUG [AnalyticsService] Received spread-stat message.
2018-02-02 16:40:09.850 INFO [SimpleSpreadStatHandler] μ: 1.202, σ: 0.122, n: 329 => minTargetProfitPercent: 1.324
2018-02-02 16:40:09.850 DEBUG [AnalyticsService] Sending to config store... {"minTargetProfitPercent":1.324}
2018-02-02 16:40:09.874 DEBUG [JsonConfigStore] Config updated with {"minTargetProfitPercent":1.324}
2018-02-02 16:40:09.975 DEBUG [AnalyticsService] Reply from config store: [object Object]
2018-02-02 16:40:11.196 DEBUG [PositionService] Refreshing positions...
2018-02-02 16:40:11.196 DEBUG [WebClient] Sending HTTP request... URL: https://coincheck.com/api/exchange/leverage/positions?limit=20&status=open&order=desc Request: {"method":"GET","headers":{"ACCESS-KEY":"QCjwXpw2HPzc-0tb","ACCESS-NONCE":"1517557211196","ACCESS-SIGNATURE":"c6d25654bcff3c66ccab5be76c2a16bf48785f021b80aa312331a06ebfcac420"},"body":""}
2018-02-02 16:40:11.197 DEBUG [WebClient] Sending HTTP request... URL: https://api.bitflyer.jp/v1/me/getpositions?product_code=FX_BTC_JPY Request: {"method":"GET","headers":{"Content-Type":"application/json","ACCESS-KEY":"2sYe7bqG3SkNwrpMdEivzS","ACCESS-TIMESTAMP":"1517557211197","ACCESS-SIGN":"eb4eefeb947a26a24c95eec4cdb10a4411c7b7a155536ed5c30ee6dd9a24e68e"},"body":""}
2018-02-02 16:40:11.260 DEBUG [WebClient] Response from https://coincheck.com/api/exchange/leverage/positions?limit=20&status=open&order=desc. Status Code: 200 (OK) 
2018-02-02 16:40:11.261 DEBUG [WebClient] Response content from https://coincheck.com/api/exchange/leverage/positions?limit=20&status=open&order=desc: {"success":true,"pagination":{"limit":20,"order":"desc","starting_after":null,"ending_before":null},"data":[]}
2018-02-02 16:40:11.290 DEBUG [WebClient] Response from https://api.bitflyer.jp/v1/me/getpositions?product_code=FX_BTC_JPY. Status Code: 200 (OK) 
2018-02-02 16:40:11.290 DEBUG [WebClient] Response content from https://api.bitflyer.jp/v1/me/getpositions?product_code=FX_BTC_JPY: []

**Comment by bitrinjani** [comment]
再インストールはしましたか?

**Comment by unitarocom** [comment]
ありがとうございます！
uninstallと再installは試してませんでしたので本日夜試させていただきます。


2018年2月3日(土) 8:18 Project Rinjani <notifications@github.com>:

**Comment by Connie-Wild** [comment]
debug.logのエラーはAPIのエラーを検知し、Stabilityが規定値(恐らく8)を下回ったために、裁定取引の算出基準から取引所が除外されたために、ベストヒットが見つからなかった事象になるので、最初に申告された事象とは異なります。
またdebag.logにはAPIキーが含まれますが、その部分も添付されているため、取引所のAPIキーを即刻作り直す事をオススメします。

**Comment by unitarocom** [comment]
失礼いたしました。
作り直しました。

**Comment by Connie-Wild** [comment]
@unitarocom さん
APIキーが漏洩した場合には悪意のある人から勝手に取引が行われたり、送金されたりといった不利益を被ることになる可能性があります。
coincheck社のように不正送金等の標的になりたくないようでしたら、APIキーの取扱には十分ご注意ください。

**Comment by unitarocom** [comment]
現状CCがAPI取引停止していることと、QUOINEXの口座ができてませんので実取引ができるようになったら改めて稼働させてみます。
本件クローズでお願いいたします。
ご返答ありがとうございます。
